In [1]:
import numpy as np
import sys
import random

In [2]:
#for delete empty lines in txt and write new
#with open("din_kulturu.txt","r", encoding = "utf-8") as f, open("outfile.txt","w", encoding = "utf-8") as outfile:
# for i in f.readlines():
#       if not i.strip():
#           continue
#       if i:
#           outfile.write(i)

In [3]:
#with open("outfile.txt","r", encoding = "utf8") as file:

In [4]:
#for creating 100 text files.Auto name files with outputbase.Splitlen split text until that line
#splitLen = 400         # 20 lines per file
#outputBase = 'religious_culture' # output.1.txt, output.2.txt, etc.

#input = open('outfile.txt', 'r' ,encoding = "utf8")

#count = 0
#at = 0
#dest = None
#for line in input:
#    if count % splitLen == 0:
#        if dest: dest.close()
#        dest = open(outputBase + str(at+1) + '.txt', 'w',encoding = "utf8")
#        at += 1
#    dest.write(line)
#    count += 1       

In [5]:
def smith_waterman_distance(line1, line2, match=3, substitution=-2, insertion=-2, deletion=-2):
    # switch sequences, so that line1 is the longer sequence to search for line2
    icoor=[]
    jcoor=[]
    if len(line2) > len(line1): line1, line2 = line2, line1
    # create the distance matrix
    mat = np.zeros((len(line2) + 1, len(line1) + 1))
    # iterate over the matrix column wise
    for i in range(1, mat.shape[0]):
        # iterate over the matrix row wise
        for j in range(1, mat.shape[1]):
            # set the current matrix element with the maximum of 4 different cases
            mat[i, j] = max(
                # negative values are not allowed
                0,
                # if previous character matches increase the score by match, else decrease it by substitution
                mat[i - 1, j - 1] + (match if line1[j - 1] == line2[i - 1] else substitution),
                # one character is missing in line2, so decrease the score by deletion
                mat[i - 1, j] + deletion,
                # one additional character is in line2, so decrease the scare by insertion
                mat[i, j - 1] + insertion
            )
            if (line1[j - 1]==line2[i - 1]):
                icoor.append(i-1)
                jcoor.append(j-1)
                
            
    # the maximum of mat is now the score, which is returned raw or normalized (with a range of 0-1)
    for k in range(len(icoor)):
        print("Matched lines are")
        print("1: ", line1[jcoor[k-1]],",j:Coordinate: ", jcoor[k-1])
        print("2: ", line2[icoor[k-1]],",i:Coordinate: ", icoor[k-1])
        print(mat[icoor[k]-5:icoor[k]+5,jcoor[k]-5:jcoor[k]+5])
        print("******************************************************")
    

In [6]:
#randomInsertionCount = random.randint(20, 30) insert string 20-30 times

In [7]:
#with open("turkish_literature5.txt", "r",encoding = "utf-8") as f: open file and take lines for manuplate
#    contents = f.readlines() 

In [8]:
#for i in range(randomInsertionCount):
#    randomLineNumber = random.randint(0, 399)  insert line between tis range
#    print(randomLineNumber)
#    contents.insert(randomLineNumber, "ThisIsTestLineForAlgorithm\n") Insert control line

In [9]:
#with open("turkish_literature5.txt", "w",encoding = "utf-8") as f: write new lines
#    contents = "".join(contents)
#    f.write(contents)

In [10]:
def readDataFromFile():  
    # create empty lists
    lines = []
  
    # open file for reading
    with open("basic_religious_knowledge1.txt", 'r', encoding = "utf-8") as f:
        for line in f.readlines():
 
            # decode each line from file
            data = line.strip('n')
            data = data.split(',')
  
            # add data to lists
            lines.append(data[0])
            
  
    return lines

def readDataFromFile2():  
    # create empty lists
    lines = []  
  
    # open file for reading
    with open("physics1.txt", 'r', encoding = "utf-8") as f:
        for line in f.readlines():
 
            # decode each line from file
            data = line.strip('n')
            data = data.split(',')
  
            # add data to lists
            lines.append(data[0])
            
  
    return lines

  
#MAIN PROGRAM
lines= readDataFromFile()
lines2= readDataFromFile2()

smith_waterman_distance(lines, lines2, 3, -2, -2, -2)

        

Matched lines are
1:  ThisIsTestLineForAlgorithm
 ,j:Coordinate:  407
2:  ThisIsTestLineForAlgorithm
 ,i:Coordinate:  394
[]
******************************************************
Matched lines are
1:  MİLLÎ EĞİTİM BAKANLIĞI
 ,j:Coordinate:  1
2:  MİLLÎ EĞİTİM BAKANLIĞI
 ,i:Coordinate:  0
[]
******************************************************
Matched lines are
1:  HAYAT BOYU ÖĞRENME GENEL MÜDÜRLÜĞÜ
 ,j:Coordinate:  2
2:  HAYAT BOYU ÖĞRENME GENEL MÜDÜRLÜĞÜ
 ,i:Coordinate:  1
[]
******************************************************
Matched lines are
1:  YAZARLAR
 ,j:Coordinate:  5
2:  YAZARLAR
 ,i:Coordinate:  4
[[6. 4. 2. 0. 0. 0. 0. 0. 0. 0.]
 [4. 4. 2. 0. 0. 0. 0. 0. 0. 0.]
 [2. 2. 2. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 5. 3. 1. 0. 0. 0. 0.]
 [0. 0. 0. 3. 3. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 4. 2. 0. 0.]
 [0. 0. 0. 0. 0. 0. 2. 2. 5. 3.]
 [0. 0. 0. 0. 0. 0. 0. 0. 3. 8.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 6.]]
***********************************************

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 3. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
******************************************************
Matched lines are
1:  ThisIsTestLineForAlgorithm
 ,j:Coordinate:  308
2:  ThisIsTestLineForAlgorithm
 ,i:Coordinate:  254
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 3. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
******************************************************
Matched lines are
1:  ThisIsTestLineForAlgorithm
 ,j:Coordinate:  330
2:  ThisIsTestLineForAlgorithm
 ,i:C